# Generated by Django 5.1.6 on 2025-02-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_portfolio_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
